server:
  port: 7000
  error:
    include-message: always

app:
  product-service:
    host: localhost
    port: 7001
  recommendation-service:
    host: localhost
    port: 7002
  review-service:
    host: localhost
    port: 7003

logging:
  level:
    root: INFO
    com.jkc.microservices: DEBUG

---

spring:
  profiles: docker
server:
  port: 7004

app:
  product-service:
    host: product
    port: 7004
  recommendation-service:
    host: recommendation
    port: 7004
  review-service:
    host: review
    port: 7004