server:
  port: 7000
  error:
    include-message: always

app:
  product-service:
    host: localhost
    port: 7001
  recommendation-service:
    host: localhost
    port: 7002
  review-service:
    host: localhost
    port: 7003

logging:
  level:
    root: INFO
    com.jkc.microservices: DEBUG

# Swagger Data
api:
  common:
    version: '0.0.1'
    title: 'product-composite-service'
    description: 'a product api'
    termsOfServiceUrl: Open Source
    license: Apache 2.0 Open Source
    licenseUrl: 'http://www.apache.org/licenses/LICENSE-2.0'
    contact:
      name: Absolute Chemist
      url: 'https://github.com/JatinderKumarChaurasia/Product-Manager'
      email: 'absolutechemist@gmail.com'
  product-composite:
    get-composite-product:
      description: Returns a composite view of the specified product id
      notes: |
        # Normal response
        If the requested product id is found the method will return information regarding:
        1. Base product information
        1. Reviews
        1. Recommendations
        1. Service Addresses\n(technical information regarding the addresses of the microservices that created the response)
        # Expected partial and error responses
        In the following cases, only a partial response be created (used to simplify testing of error conditions)
        ## Product id 113
        200 - Ok, but no recommendations will be returned
        ## Product id 213
        200 - Ok, but no reviews will be returned
        ## Non numerical product id
        400 - A <b>Bad Request</b> error will be returned
        ## Product id 13
        404 - A <b>Not Found</b> error will be returned
        ## Negative product ids
        422 - An <b>Unprocessable Entity</b> error will be returned

---

spring:
  profiles: docker
server:
  port: 7004

app:
  product-service:
    host: product
    port: 7004
  recommendation-service:
    host: recommendation
    port: 7004
  review-service:
    host: review
    port: 7004